### PR TITLE
add ncnn backend

### PR DESCRIPTION
**Pull request by caishanli**
add ncnn backend
fix run with one backend must install all other backends

### CODE REVIEW

**Comment by nihui** [comment]
why is the source demo_mnn/python/demo_mnn.py ?

**Comment by caishanli** [comment]
I run with onnx backend with nanodet.onnx, everything is ok.
But when I export nanodet.onnx to ncnn and run, no object detected. 
Help!

**Comment by caishanli** [comment]
> why is the source demo_mnn/python/demo_mnn.py ?

I don't know.
This file contain torch mnn onnx.

**Comment by RangiLyu** [comment]
Sorry, can you move the ncnn Python demo to demo_ncnn folder?

**Comment by caishanli** [comment]
> Sorry, can you move the ncnn Python demo to demo_ncnn folder?

why both of you only care about the code path...

**Comment by RangiLyu** [comment]
> > Sorry, can you move the ncnn Python demo to demo_ncnn folder?
> 
> why both of you only care about the code path...

Cuz the wrong path will mislead users... 
Now we have python demos with onnx, mnn, ncnn and PyTorch backends. Should all of these python demos be put in one folder or independently? Let's discuss this issue later...
By the way, is the pyncnn demo producing the correct result?

**Comment by caishanli** [comment]
> > > Sorry, can you move the ncnn Python demo to demo_ncnn folder?
> > 
> > 
> > why both of you only care about the code path...
> 
> Cuz the wrong path will mislead users...
> Now we have python demos with onnx, mnn, ncnn and PyTorch backends. Should all of these python demos be put in one folder or independently? Let's discuss this issue later...
> By the way, is the pyncnn demo producing the correct result?

no, the same preprocess and postprocess as onnx, only infer with ncnn, I don't know why get wrong result.

**Pull request merged**
